### PR TITLE
RemoveUnusedLocalVariables fails inside case blocks (test)

### LINKED ISSUE #152: RemoveUnusedLocalVariables fails inside case blocks
## What version of OpenRewrite are you using?

I am using

- rewrite-java:8.2.0-SNAPSHOT

## How are you running OpenRewrite?

Inside the rewrite-static-analysis repo; as a test

## What is the smallest, simplest way to reproduce the problem?

```java
class Test {
    static void method() {
        int x = 10;
        char y = 20;
        switch (x) {
            case 10:
                byte unused;
                break;
        }
    }
}
```

results in

```java
class Test {
    static void method() {
        int x = 10;
        char y = 20;
        switch (x) {
            case 10:
                byte; // <-- mistake here
                break;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by sfc-gh-dtran**
## What's your motivation?

Fixes #152 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ auto-formatter on affected files
- [x] I've updated the documentation (if applicable)

### CODE REVIEW

**Comment by timtebeek** [comment]
Appreciate you adding this test! There's a bit of an oddity where you also remove two other tests. Would you mind reverting that?

**Comment by sfc-gh-dtran** [comment]
> Appreciate you adding this test! There's a bit of an oddity where you also remove two other tests. Would you mind reverting that?

Thanks, that was weird indeed. I re-added those missing tests.

**Comment by timtebeek** [comment]
Thanks! I've ran your test and briefly explored the options; the quickest thing we can do now to avoid making unwanted changes, is to simply skip unused variables defined in case statements. That's a bit unfortunate, but better than making the wrong change right now. We can then later look to also remove unused local variables inside case statements. Hope you agree!

**Comment by sfc-gh-dtran** [comment]
> Thanks! I've ran your test and briefly explored the options; the quickest thing we can do now to avoid making unwanted changes, is to simply skip unused variables defined in case statements. That's a bit unfortunate, but better than making the wrong change right now. We can then later look to also remove unused local variables inside case statements. Hope you agree!

Thanks! I've actually already looked into this and it looks like the problem is with the `DeleteStatement` recipe not handling statements inside case blocks: adding a simple `visitCaseBlock` visitor fixed this; I can make a PR to `rewrite` so you can take a look at it

**Pull request merged**
