### PR TITLE
`RemoveUnusedPrivateMethods` should ignore class annotated with `@SupressWarning("unused")`

### LINKED ISSUE #294: org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods ignores class level @SuppressWarnings("unused")
## What version of OpenRewrite are you using?
6.6.3

## What is the smallest, simplest way to reproduce the problem?
```java
@SuppressWarnings("unused")
class A {
    @SuppressWarnings("unused")
    private static void foo() {
    }

    private void bar() {
    }

}
```

## What did you expect to see?

```java
@SuppressWarnings("unused")
class A {
    @SuppressWarnings("unused")
    private static void foo() {
    }

    private void bar() {
    }

}

```

## What did you see instead?

```java
@SuppressWarnings("unused")
class A {
    @SuppressWarnings("unused")
    private static void foo() {
    }

}
```

The looks like that https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java#L62 doesn't look at the class level annotation and is also just assuming that any class annotation means don't do anything.  IT should look for     @SuppressWarnings("unused") at the class level.

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

### PR DESCRIPTION
**Pull request by Dinozavvvr**
Fix #294
- #294

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks a lot for the start @Dinozavvvr ! As indicated in the issue we'll likely want to add an override of `visitClassDeclaration`, that uses `FindAnnotations` to [find the suppress annotation on the class](https://github.com/openrewrite/rewrite/blob/9f634a3bf3385dd127e7cc15d54836b1a25ae578/rewrite-java/src/main/java/org/openrewrite/java/search/FindAnnotations.java#L38), inspects the value, and if that contains `unused` then do not call `super.visitClassDeclaration`, but return the original argument classDeclaration. That'll be in between these lines in the recipe itself.
https://github.com/openrewrite/rewrite-static-analysis/blob/b7b1bd1fd82c5e713d7ea5777375c6daf6eb9067/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java#L55-L57

**Comment by Dinozavvvr** [comment]
@timtebeek thank you a lot for your suggestion!

**Comment by Dinozavvvr** [comment]
@timtebeek I found that solution based on visiting J.ClassDeclaration ignores nested classes, so I moved this check to visitMethodDeclaration. Is there another better way to do so or maybe I'm wrong please correct

**Comment by Dinozavvvr** [comment]
Did it

**Comment by timtebeek** [comment]
Great to see you've worked this out @Dinozavvvr ! I've added a small polishing commit to better fit in with our code conventions. Seems like a handy pattern to limit recipe execution by looking for suppressed warnings. We might just want to apply that in a few more cases, or pull this up to a higher level even. Neat stuff!

**Review by timtebeek — APPROVED** [review]

**Pull request merged**
